### ISSUE TITLE
60Hz Refresh rate?

### ISSUE THREAD

**Issue by PathToLife** [in-sideFX/UndecoratorBis#11]
Hi there,

Sorry for bringing refresh rate up, I know it sounds picky.
Our app is to be built to 2018 standards with a gaming user base, calling these guys picky is a understatement.

Every other window on our monitors, including UI intensive IntelliIJ, is able to be dragged around at a smooth nice 165HZ.
UndercoratorBis.jar feels like it barely hits 30HZ(Fps) when dragged.

Our application will moved around quite a lot, similar usage to discord, and this refresh rate limitation would be a impact to the first time use experience. Any idea what causes it?

I'm not asking for a fix, as that'll be unfair, but just some preliminary information to help us and others solve this problem.

Cheers, PTL

**Comment by in-sideFX** [comment]
Hi,
Do you experience the same with a basic JavaFX démo sample? Ensemble for instance?
Thanks

**Comment by PathToLife** [comment]
Hi,
Thanks for the quick reply.

Looks like java abandoned the frameless stage in their demo.
We have concluded that Javafx is not suited to our needs and have moved to chromium frameless =)

![image](https://user-images.githubusercontent.com/12622625/35191772-a5224c52-fee8-11e7-95e6-b1c1d858076b.png)

Javafx will be our preferred UI/UX framework for security intensive, long term support applications.

But for powerful, beautiful looking desktop apps:
GO CSS and Chromium!
To make a window dragable, including OS default quick resize, we just do:
![image](https://user-images.githubusercontent.com/12622625/35191780-d874e74a-fee8-11e7-845b-32e15e04801f.png)

Cheers
