### ISSUE TITLE
Fullscreen button not working properly

### ISSUE THREAD

**Issue by SaeedMasoumi** [in-sideFX/UndecoratorBis#2]
Hi,
I'm using your latest version. Whenever I click on fullscreen button, nothing happens.
<img width="1103" alt="screen shot 2016-04-01 at 11 00 25 pm" src="https://cloud.githubusercontent.com/assets/6934577/14216431/f1771bde-f85d-11e5-97f1-b2865353d5e3.png">

**Comment by in-sideFX** [comment]
Hi, 
You're running on a Mac, aren't you?
There is a JavaFX issue since Java8 when using full screen mode with undecorated window. 
Everything is ok on Windows...
Hope it's going to be fixed...

**Comment by SaeedMasoumi** [comment]
Oh, yes i'm on mac. Thank you.
